name: 'hotel_analytics_pipeline'
version: '1.0.0'
config-version: 2

profile: 'hotel_analytics_pipeline'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  hotel_analytics_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
